### ISSUE TITLE
SERVICES: links with the same name must have similar purpose

### ISSUE THREAD

**Issue by chuckcarpenter** [shipshapecode/website-astro#9]
In order to differentiate, links to view more info on technologies must be more specific

**Comment by hannakim91** [comment]
Seems like this might be ok to leave them as "learn more" and "see it in action" since it makes sense in the context of each card. However, it may be good to make these links more visibly different - either turn them into buttons or bump up the contrast between the text above by bolding/underlining text, or maybe turn them into buttons?

https://uxdesign.cc/designing-better-links-for-websites-and-emails-a-guideline-5b8638ce675a
